### ISSUE TITLE
module 'Cython' has no attribute 'Distutils'

### ISSUE THREAD

**Issue by zerospirit79** [flupke/cython-setuptools#5]
Cython.Distutils.build_ext definitely exists, but some voodoo is causing it it disappear.

My guess is that the sys.modules hack needs a bit of work. IIRC, to delete a package, all sub-modules also need to be removed from sys.modules.

Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 447, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 740, in finalize_options
    ep(self)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/setuptools_cython.py", line 21, in <module>
    class build_cython(Cython.Distutils.build_ext, object):
AttributeError: module 'Cython' has no attribute 'Distutils'

**Comment by zerospirit79** [comment]
Wrong comment. I was build package. Problem was with another attribute.
